'use client';

import React, { Suspense } from 'react';
import { AuthGuard } from '@/components/auth/auth-guard';
import { AIDoctorTools } from '@/components/doctor/ai-doctor-tools';
import { AiStatusBanner } from '@/components/doctor/ai-status-banner';

/**
 * Clinical AI Suite — a page of its own rather than a block on the dashboard.
 * Everything here calls Ollama live through /api/ai/*; nothing is precomputed.
 */
export default function DoctorAiSuitePage() {
  return (
    <AuthGuard allowedRoles={['DOCTOR']}>
      <Suspense
        fallback={
          <div className="panel blank-panel">
            <div className="blank-state">
              <i className="bi bi-hourglass-split" aria-hidden="true" />
              <p className="text-muted mb-0">Loading the clinical AI suite…</p>
            </div>
          </div>
        }
      >
        <div className="page-heading">
          <div className="page-heading-copy">
            <span className="page-icon">
              <i className="bi bi-stars text-warning" aria-hidden="true" />
            </span>
            <div>
              <p className="eyebrow mb-1">Decision Support</p>
              <h1 className="h3 mb-1">Clinical AI Suite</h1>
              <p className="text-muted mb-0">
                Every request is answered live by a panel of Ollama Cloud models; the answer they agree on is the one
                shown, tagged with the model that produced it.
              </p>
            </div>
          </div>
        </div>

        <AiStatusBanner />

        <AIDoctorTools />

        <section className="panel mt-3">
          <div className="panel-header">
            <div>
              <h2 className="h5 mb-1 section-title">
                <i className="bi bi-shield-exclamation" aria-hidden="true" />
                <span>How to read these results</span>
              </h2>
            </div>
          </div>
          <ul className="text-muted small mb-0 ps-3">
            <li>
              Each result carries the model that produced it and the panel&apos;s agreement score. Low agreement means
              the models disagreed — read that suggestion more carefully.
            </li>
            <li>
              A grey <strong>Rule engine (AI offline)</strong> badge means no model could be reached. Nothing on screen
              was generated by AI in that case, and no diagnosis or prescription is suggested.
            </li>
            <li>
              This is decision support. Every diagnosis, dose and order needs your clinical judgement before it reaches
              a patient record.
            </li>
          </ul>
        </section>
      </Suspense>
    </AuthGuard>
  );
}
